### ISSUE TITLE
Consider using HIPPO_SERVER_URL instead?

### ISSUE THREAD

**Issue by carolynvs** [deislabs/hippofactory#25]
It would be helpful if our environment variables between bindle and hippo followed the same naming conventions. Right now we have BINDLE_SERVER_URL and HIPPO_SERVICE_URL which is super easy for a user to get confused. If they both used SERVER or SERVICE, that would make it a lot less likely that the environment variables are declared incorrectly.

**Comment by itowlson** [comment]
Yeah, I'm not sure what the best convention is.  Bindle already established `BINDLE_SERVER_URL` but that felt wrong for Hippo because Hippo is meant to be a service somewhere _waves hands_ out there, rather than a physical server.  Maybe I should just use `HIPPO_URL` as being slightly less asymmetric...?

**Comment by carolynvs** [comment]
If the problem is in the word service vs server, you could call them both BINDLE_ENDPOINT and HIPPO_ENDPOINT? 😁 

I am not in a position to say what's the right change to make, just wanted to call out that what we have right now is very easy to get mixed up.

**Comment by bacongobbler** [comment]
Kubernetes' convention is *_SERVICE_URL. If we follow that convention and deployed Hippo to Kubernetes, we'd gain free compatibility through the Service API.

That being said, I highly doubt that our intended use case is for hippofactory to be used within Kubernetes... I'd imagine users would implement a wrapper around hippofactory if it were used in a Kubernetes context.

I'm partial to `BINDLE_URL` and `HIPPO_URL` personally. It's shorter and removes the "service" and/or "server" convention, which is more of an implementation detail.

**Comment by carolynvs** [comment]
+1 for *_URL

**Comment by itowlson** [comment]
@technosophos Petition for a diet or conclave to lay down a firm credo on environment variables and authorise a papal commission to root out noncompliance

**Comment by technosophos** [comment]
`*_URL` it shall be. It does make more sense to say "service" than "server", but I am in favor of brevity whenever possible.

I'll go ahead and take the task of fixing this in Bindle.
