### ISSUE TITLE
Add more detail to error when a handler doesn't exist yet

### ISSUE THREAD

**Issue by carolynvs** [deislabs/hippofactory#26]
1. Run yo-wasm and create a project
2. Run it with cargo but don't compile it targeting wasm32-wasi --release.
3. The hipppofacts handler for your default project references a handler that hasn't been built yet `target/wasm32-wasi/release/whalesay.wasm`.
4. Run hippofactory and note that the error doesn't tell you what file it tried to use

```
$ hippofactory -k HIPPOFACTS
Error: No such file or directory (os error 2)
```

It would have saved me about 30 minutes of debugging to realize that it was failing to find the compiled handler. 😂

**Comment by itowlson** [comment]
I'm sorry for your wasted time!  Agree this and plenty of other things need an error pass - I have focused on the happy path to get the demo working and it is long past time to deal with the sad path too!

**Comment by carolynvs** [comment]
No need to apologize, that's what I'm trying to help with. Finding spots where things get confusing and either help with docs or provide feedback to the team. I live on the sad path. 😀

**Comment by itowlson** [comment]
Now prints "Error: Could not assemble parcel for file /home/ivan/tests/yotests/moar-toast-on-demand/target/wasm32-wasi/release/no-moar-toast-on-demand.wasm: No such file or directory (os error 2)"

Please reopen if there are still cases where the unhelpful form still occurs.
