### ISSUE TITLE
Error message: File not found error with no path

### ISSUE THREAD

**Issue by technosophos** [deislabs/hippofactory#28]
I am getting this error message:

```console
$ hippofactory HIPPOFACTS -a prepare --dir _scratch
Error: No such file or directory (os error 2)
```

I think the problem is that my `HIPPOFACTS` points to a `target/wasm32-wasi/release/cgi-rust.wasm`, but the module is actually in `target/wasm32-wasi/debug/cgi-rust.wasm`

I think all we need is a better error message

**Comment by technosophos** [comment]
I am also not sure why my `cargo build-wasm` builds to the debug path instead of the `release` path.

**Comment by itowlson** [comment]
Duplicate of #26
